use crate::models::Product;

pub fn init_mock_data() -> Vec<Product> {
    vec![
        Product {
            id: 1,
            name: "Nike Air Max rust".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 2,
            name: "Adidas Ultra Boost".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 3,
            name: "T-Shirt".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 4,
            name: "Nike Air Max".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 5,
            name: "Adidas Ultra Boost".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 6,
            name: "T-Shirt".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 7,
            name: "Nike Air Max 2".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 8,
            name: "Adidas Ultra Boost 2".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 9,
            name: "T-Shirt 2".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 10,
            name: "Nike Air Max 3".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 11,
            name: "Nike Air Max rust".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 12,
            name: "Adidas Ultra Boost".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 13,
            name: "T-Shirt".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 14,
            name: "Nike Air Max".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 15,
            name: "Adidas Ultra Boost".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 16,
            name: "T-Shirt".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 17,
            name: "Nike Air Max 2".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 18,
            name: "Adidas Ultra Boost 2".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 19,
            name: "T-Shirt 2".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 20,
            name: "Nike Air Max 3".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 21,
            name: "Nike Air Max rust".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 22,
            name: "Adidas Ultra Boost".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 23,
            name: "T-Shirt".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 24,
            name: "Nike Air Max".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 25,
            name: "Adidas Ultra Boost".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 26,
            name: "T-Shirt".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 27,
            name: "Nike Air Max 2".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 28,
            name: "Adidas Ultra Boost 2".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 29,
            name: "T-Shirt 2".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 30,
            name: "Nike Air Max 3".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 31,
            name: "Nike Air Max rust".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 32,
            name: "Adidas Ultra Boost".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 33,
            name: "T-Shirt".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 34,
            name: "Nike Air Max".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 35,
            name: "Adidas Ultra Boost".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 36,
            name: "T-Shirt".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 37,
            name: "Nike Air Max 2".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 38,
            name: "Adidas Ultra Boost 2".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 39,
            name: "T-Shirt 2".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 40,
            name: "Nike Air Max 3".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 41,
            name: "Nike Air Max rust".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 42,
            name: "Adidas Ultra Boost".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 43,
            name: "T-Shirt".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 44,
            name: "Nike Air Max".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 45,
            name: "Adidas Ultra Boost".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 46,
            name: "T-Shirt".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 47,
            name: "Nike Air Max 2".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 48,
            name: "Adidas Ultra Boost 2".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 49,
            name: "T-Shirt 2".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 50,
            name: "Nike Air Max 3".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 51,
            name: "Nike Air Max rust".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 52,
            name: "Adidas Ultra Boost".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 53,
            name: "T-Shirt".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 54,
            name: "Nike Air Max".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 55,
            name: "Adidas Ultra Boost".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 56,
            name: "T-Shirt".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 57,
            name: "Nike Air Max 2".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 58,
            name: "Adidas Ultra Boost 2".to_string(),
            price: 179.99,
            image: "/assets/images/adidas-ultraboost.jpg".to_string(),
            description: "Comfortable running shoes".to_string(),
            category: "Shoes".to_string(),
        },
        Product {
            id: 59,
            name: "T-Shirt 2".to_string(),
            price: 19.99,
            image: "/assets/images/tshirt.jpeg".to_string(),
            description: "Comfortable cotton t-shirt".to_string(),
            category: "Clothes".to_string(),
        },
        Product {
            id: 60,
            name: "Nike Air Max 3".to_string(),
            price: 199.99,
            image: "/assets/images/nike.jpg".to_string(),
            description: "Classic Nike Air Max sneakers".to_string(),
            category: "Shoes".to_string(),
        },
    ]
} 